access_openhealth_doctor,access_openhealth_doctor,model_openhealth_doctor,,1,1,1,1
access_openhealth_coder,access_openhealth_coder,model_openhealth_coder,,1,1,1,1
access_openhealth_service_consultation,access_openhealth_service_consultation,model_openhealth_service_consultation,,1,1,1,1
access_openhealth_corrector,access_openhealth_corrector,model_openhealth_corrector,,1,1,1,1
access_openhealth_scheduler,access_openhealth_scheduler,model_openhealth_scheduler,,1,1,1,1
access_openhealth_configurator,access_openhealth_configurator,model_openhealth_configurator,,1,1,1,1
access_openhealth_configurator_report,access_openhealth_configurator_report,model_openhealth_configurator_report,,1,1,1,1

access_db_backup,access_db_backup,model_db_backup,,1,1,1,1



access_price_list_product,access_price_list_product,model_price_list_product,,1,1,1,1
access_price_list_product_selector,access_price_list_product_selector,model_price_list_product_selector,,1,1,1,1
access_price_list_service,access_price_list_service,model_price_list_service,,1,1,1,1
access_price_list_container,access_price_list_container,model_price_list_container,,1,1,1,1

